# Generated by Django 3.2.9 on 2021-12-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20211203_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ('user__first_name',), 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
