# Generated by Django 3.2.9 on 2021-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_alter_aluno_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_aluno',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
