# Generated by Django 4.2.26 on 2025-11-17 02:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_aluno_foto_aluno'),
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código usado para composição de turmas e matrículas', max_length=10, unique=True, verbose_name='Código do Curso')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ppc', models.FileField(blank=True, default=None, null=True, upload_to='static/', verbose_name='PPC')),
                ('ch_total', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Carga Horária Total do Curso')),
                ('tipo_hora_aula', models.PositiveIntegerField(blank=True, choices=[[45, '45 min'], [60, '60 min']], null=True, verbose_name='Tipo Hora Aula')),
                ('periodicidade', models.PositiveIntegerField(choices=[[1, 'Anual'], [2, 'Semestral'], [3, 'Livre']], null=True, verbose_name='Periodicidade')),
                ('media_aprovacao', models.DecimalField(blank=True, decimal_places=2, help_text='Valor entre 0 e 10.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Média para aprovação')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ('id', 'ativo'),
            },
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula de Aluno', 'verbose_name_plural': 'Matrículas de Aluno'},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='nome_aluno',
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comum_aluno', to='comum.aluno', verbose_name='Aluno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_curso', to='edu.curso', verbose_name='Curso'),
        ),
    ]
